name: Daily Auto Commit

on:
  workflow_dispatch:  # Allows manual run
  schedule:
    - cron: '0 5 * * *'  # 🔄 Runs daily at 10:30 AM IST

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Clear and Update .txt Files
        run: |
          find . -name "*.txt" -type f -exec sh -c '> "$1"' _ {} \;
          touch daily-log.txt
          echo "Updated on $(date)" >> daily-log.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Mahesh27072004"
          git config --global user.email "navnathsanap976@gmail.com"
          git add .
          git commit -m "Auto update: $(date)" || echo "No changes to commit"
          git push
